### ISSUE TITLE
Feature request: ask a `Scope` how many threads are running

### ISSUE THREAD

**Issue by ocharles** [awkward-squad/ki#17]
As the issue title says, I'd love to monitor my top-level scope to make sure that my forked threads are actually terminating.

**Comment by mitchellwrosen** [comment]
Interesting use case. Currently, there's no way for a scope to count all of the threads created within it (transitively) - we only have the direct children. Does that limit the usefulness of such a function, like `scopeChildrenCount :: Scope -> TVar Int`?

**Comment by ocharles** [comment]
I think that would limit the usefulness, yea. Can a `Scope` not keep track of its children, and then we can transitively make this calculation? I would also have a type more like `scopeChildrenCount :: Scope -> STM Int` (so I can't write to it, nor do I care what it's backed by)

**Comment by mitchellwrosen** [comment]
(Ah, yeah, STM Int - my bad).

A Scope could keep track of its children, but it would require a little extra coordination/contention (e.g. a global mapping from ThreadId to Scope, and maybe some other stuff inside the Scope).

I'm not against that - it seems useful for debugging at the very least - and was in fact similar to how the library used to work (except we avoided the global data structure by requiring a Scope to create a Scope, essentially). But it would need some design, and I wonder if it might ultimately belong better in some kind of companion `ki-debug` package. Other ideas for such a package include allowing the user to provide callbacks for certain events the library sees, such as a thread spawning, dying, etc.

But anyway, in the meantime, could this be adequately solved in user-space by just bracketing your `fork` calls with a `plus1`/`minus1` counter? I realize it's not elegant, but (depending on your precise use case) for debugging things it needn't be ;)

(Also, could the eventlog help?)

**Comment by ocharles** [comment]
I realise now that a `Scope` can't keep track of its children because it doesn't have a direct link. I forgot that we have `scoped :: (Scope -> IO a) -> IO a)`, rather than `scoped :: Scope -> (Scope -> IO a) -> IO a`, so keeping track of transitive scopes is much harder. I know that Ben is working on more instrumentation for threads in GHC itself, which might ultimately do what I want. Failing that, maybe `ki-instrumented` is a better option, as you say.

**Comment by TristanCacqueray** [comment]
I'm also looking for this feature, and it sounds like it would be easier to query GHC itself. @ocharles, would you have a link to the new work on instrumentation for threads? Is there a way to get the list of running thread already?

**Comment by ocharles** [comment]
@TristanCacqueray https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2816

**Comment by mitchellwrosen** [comment]
@ocharles Do you think this issue was "resolved" by the potential for better thread introspection utils in GHC? I'm happy to leave it open for more discussion, if not.
