### ISSUE TITLE
Feature request: a way to cancel threads

### ISSUE THREAD

**Issue by ocharles** [awkward-squad/ki#18]
It'd be nice if we had a `cancel :: Thread a -> IO ()` action, or something similar. Is that possible?

**Comment by mitchellwrosen** [comment]
FWIW, [libdill](http://libdill.org/index.html) doesn't provide this function either, only "bundle.close()" (kill all threads in a scope).

**Comment by ocharles** [comment]
Haha, wow, I don't remember that discussion but I agree with this ocharles guy! I'll take my own suggestion and use an MVar to signal early termination

**Comment by mitchellwrosen** [comment]
@TristanCacqueray Feel free to continue the discussion in #12 (perhaps by just copying that comment). I'll refrain from responding in this closed issue, for discoverability
